spring:
  application:
    name: rest-spring-application
  datasource:
    url: jdbc:mysql://localhost:3306/rest_spring_application?useTimezone=true&serverTimezone=UTC
    username: ${usernameDB}
    password: ${passwordDB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

    open-in-view: false
